name: Publish Reports

on:
  schedule:
    - cron: '0 6,18 * * *'  # 6 AM and 6 PM UTC
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  pages: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 feedparser openai tenacity
          pip install "lxml[html_clean]"
          pip install newspaper3k

      - name: Summarize context
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python analysis/summarize_context.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add site/_posts/
          git commit -m "Auto: Publish new report $(date +'%Y-%m-%d %H:%M')" || echo "No changes to commit"
          git push
