name: Scrape Articles

on:
  schedule:
    - cron: '0 5 * * *'  # 5 AM UTC
  workflow_dispatch:

permissions:
  contents: write
  id-token: write
  pages: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 feedparser openai tenacity cloudscraper
          pip install "lxml[html_clean]"
          pip install newspaper3k

      - name: Scrape and save articles
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python scraper/scrape_articles.py

      - name: Commit and push articles
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add data/
          git commit -m "Auto: Update articles $(date +'%Y-%m-%d %H:%M')" || echo "No changes to commit"
          git pull --rebase origin main || (echo "Rebase failed, aborting rebase and skipping push"; git rebase --abort; exit 0)
          git push || echo "Push failed, probably due to race condition"
